config/routes.rb
LCBO::Application.routes.draw do
  get 'products' => 'products#index'
  get 'products/:id' => 'products#show', as: 'product'
  get 'products/:id/inventory' => 'products#product_inventory', as: 'inventory'
  get 'stores' => 'stores#index', as: 'stores'
  get 'stores/:id' => 'stores#store', as: 'store'

  root :to => 'products#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
require 'open-uri'
class ProductsController < ApplicationController

   def index
    products_json = open('http://lcboapi.com/products?per_page=100').read
    @products = JSON.parse(products_json)
   end

   def show
  	products_json = open("http://lcboapi.com/products/#{params[:id]}").read
  	@product = JSON.parse(products_json)

   end

   def product_inventory
  	 inventory_json = open("http://lcboapi.com/products/#{params[:id]}/inventories").read
  	 @inventory = JSON.parse(inventory_json)

   end



end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
   	stores_json = open("http://lcboapi.com/stores").read
   	@stores = JSON.parse(stores_json)
   end

   def store
   	store_json = open("http://lcboapi.com/stores/#{params[:id]}").read
   	@store = JSON.parse(store_json)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def format_price(price)
		price_in_dollars = price.to_f / 100
   		sprintf("%.2f", price_in_dollars)
	end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LCBO</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>LCBO</h1>
<%= link_to "All Stores", stores_path %>

<h2>Products</h2>
<table>
<% @products['result'].sort{|a,b| a['name'] <=> b['name']}.each do |product| %>
  <section>
  <tr>
    <td><%= link_to product['name'], product_path(product['id']) %></td>
    <td>  $<%= format_price product['price_in_cents'] %></td>
    <td>  <%= product['primary_category'] %></td>
     <td>  <%= link_to "Check Inventory", inventory_path(product['id']) %></td>
    </tr>
  </section>
 <% end %>
  </table>

app/views/products/product_inventory.html.erb
<h1>Inventory of <%= @inventory['product']['name'] %></h1>
<table>
<tr>
	<th>Store Id</th>
	<th id="quantity">Quantity</th>
</tr>
<% @inventory['result'].each do |i| %>
<tr>
	<td><%= i["store_id"] %></td>
	<td id="quantities"><%= i["quantity"] %></td>
</tr>
<% end %>

</table>

app/views/products/show.html.erb
<% @product = @product['result'] %>
<h1><%= @product["name"] %></h1>

<table>
<% @product.each do |key, value| %>
<tr>
	<td><%= "#{key} : #{value}" %></td>
</tr>
<% end %>
</table>

app/views/stores/index.html.erb
<h1>All Stores</h1>

<% @stores['result'].each do |store| %>
	<%= link_to store["name"], store_path(store["id"])  %></br>

<% end %>

app/views/stores/store.html.erb
<% @store = @store['result'] %>

<h1>Store: <%=  @store["name"] %></h1>
<table>
<% @store.each do |key, value| %>
<tr>
	<td><%= "#{key}: #{value}" %></td>
</tr>
<% end  %>
</table>